### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by alexisvincent** [tschaumburg/FastBarcodeScannerPlugin#1]
Hi there, I'm busy looking around for a quick barcode scanner. What are the goals/status of this project

**Comment by uniphonic** [comment]
I'm not a contributor, but I noticed there is more information at https://github.com/tschaumburg/FastBarcodeScanner

**Comment by alexisvincent** [comment]
@uniphonic Thanks :) Been ages since I needed this though xD
